language: php

php:
  - 5.5
  - 5.6
  - 7
  - nightly
  - hhvm

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly

before_install:
  - travis_retry composer self-update

install:
  - composer install --prefer-source

script:
  - vendor/bin/phpunit
